# MegaLinter Configuration File - Place at the ROOT of your repository
# This single file will control everything.

# 1. Disable linters you do not want to use.
DISABLE:
  - PYTHON
  - JAVASCRIPT
  - TYPESCRIPT
  - JSX
  - TSX
  - BASH
  # Disabling all SPELL linters to fix cspell and lychee errors
  - SPELL
  # Disabling security linters that are flagging issues to be addressed later
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS

# 2. Exclude specific directories from all checks.
# This must be a single string.
FILTER_REGEX_EXCLUDE: "(test-code/)"

# 3. Configure linters directly.
# This method is more reliable and self-contained.

# Configure actionlint
ACTION_ACTIONLINT:
  # Disable the check for outdated actions (e.g., checkout@v3)
  # and the integrated shellcheck.
  DISABLE_RULES:
    - action
    - shellcheck

# Configure yamllint
YAML_YAMLLINT:
  # Pass the entire configuration for yamllint here.
  CONFIG_FILE: |
    rules:
      # Disables the rule that requires YAML files to start with ---
      document-start: disable
      # Disables the check for non-standard boolean values (e.g. 'on')
      truthy: disable
      # Ignores indentation rules for comments
      comments-indentation: disable
      # Sets the maximum line length to 120 characters
      line-length:
        max: 120
      # Disables the check for trailing spaces
      trailing-spaces: disable
