disable:
  - "uses-latest-version"
  - "glob-double-quotes"
  - "unrecognized-event"
  - "shellcheck"
  - "action"
  - "syntax-check"

ignore:
  - "action is too old"
  - '"secrets" is only available for a reusable workflow call'
  - 'name is missing in "environment" section'
  - '"environment" section is sequence node but mapping node is expected'
