name: Milestone Linker

on:
  push:
  pull_request:
    types:
      - closed # Trigger on relevant PR events
    # paths: # targeting only code that touches the app
    #   - VAMobile/src/**

jobs:
  process_pr_and_issue:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    outputs:
      linked_issues_found: ${{ steps.linked_issues.outputs.linked_issues_count }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: where am I
        run: |
          pwd
          ls -al
          cd .github/workflows
          pwd
          ls -al

      - name: Check Linked Issues
        id: linked_issues
        uses: ./.github/workflows/check-linked-issues.yml
        with:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Use linked issues
        id: found_linked_issues
        run: |
          LINKED_ISSUE_NUMBER = ${{ steps.linked_issues.linked_issues_found }}
          LINKED_ISSUES_ARRAY_STR="${{ steps.linked_issues.outputs.issues }}"
          echo "Debug: Raw issues array string from 'check-linked-issues.yml': '$LINKED_ISSUES_ARRAY_STR'"
          FIRST_LINKED_ISSUE=$(echo "$LINKED_ISSUES_ARRAY_STR" | jq -r '.[0]')
          LINKED_ISSUE_NUMBER=$(echo "$FIRST_LINKED_ISSUE" | cut -d '#' -f 2)

          if [[ -z "$LINKED_ISSUE_NUMBER" ]]; then
            echo "No explicit linked issue found in PR description for PR #${{ github.event.pull_request.number }}."
            # echo "linked_issue_number=" >> $GITHUB_OUTPUT
          else
            echo "Linked issue number found: #$LINKED_ISSUE_NUMBER"
            echo "linked_issue_number=$LINKED_ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Conditional Action Add Milestone to issue or PR
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          LINKED_ISSUE_NUM="${{ steps.found_linked_issues.outputs.linked_issue_number }}"
          MILESTONE_ID=$(gh api "repos/${{ github.repository }}/milestones?sort=number&direction=asc" --jq '.[0].number')
          MILESTONE_TITLE=$(gh api "repos/${{ github.repository }}/milestones?sort=number&direction=asc" --jq '.[0].title')

          if [[ -z "$LINKED_ISSUE_NUM" ]]; then
            echo "PR Number $PR_NUM"
          else
            echo "Linked Issue Number: $LINKED_ISSUE_NUM"
          fi

          if [[ -n "$LINKED_ISSUE_NUM" ]]; then
          echo "Linked issue $LINKED_ISSUE_NUM found. Adding milestone $MILESTONE_TITLE."
            gh issue edit $LINKED_ISSUE_NUM --milestone $MILESTONE_TITLE
          else
            echo "Setting milestone $MILESTONE_TITLE" for PR $PR_NUM
            echo "Linked Issue Number: $LINKED_ISSUE_NUM"
            echo "Processing PR $PR_NUM..."
             gh pr edit $PR_NUM --milestone $MILESTONE_TITLE
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
