name: Milestone Linker

on:
  pull_request:
    types: [opened, edited, synchronize, closed] # Trigger on relevant PR events

jobs:
  process_pr_and_issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Linked Issue Number from PR Body
        id: extract_issue # ID for this step to reference its outputs
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          LINKED_ISSUE_NUMBER=""

          if [[ "$PR_BODY" =~ ([Cc]loses|[Ff]ixes|[Rr]esolves)[[:space:]]?#([0-9]+) ]]; then
            LINKED_ISSUE_NUMBER="${BASH_REMATCH[2]}"
          fi

          if [[ -z "$LINKED_ISSUE_NUMBER" ]]; then
            echo "No explicit linked issue found in PR description for PR #${{ github.event.pull_request.number }}."
            echo "linked_issue_number=" >> $GITHUB_OUTPUT
          else
            echo "Linked issue number found: #$LINKED_ISSUE_NUMBER"
            echo "linked_issue_number=$LINKED_ISSUE_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Conditional Action Add Milestone to issue or PR
        # if: github.event.pull_request.merged == true
        run: |
          MILESTONE_TITLE=$(gh api "repos/jbergman-oddball/va-test/milestones" --jq  'map(.title) | sort | .[0]')
          if [[ -z "$LINKED_ISSUE_NUM" ]]; then
            PR_NUM="${{ github.event.pull_request.number }}"
            echo "Linked Issue Number: $LINKED_ISSUE_NUM"
          else
            LINKED_ISSUE_NUM="${{ steps.extract_issue.outputs.linked_issue_number }}"
            echo "Linked Issue Number: $LINKED_ISSUE_NUM"
          fi

          if [[ -n "$LINKED_ISSUE_NUM" ]]; then
            echo "Linked issue #$LINKED_ISSUE_NUM found. Adding milestone $MILESTONE_TITLE."
            gh issue edit $LINKED_ISSUE_NUM --milestone $MILESTONE_TITLE
          else
            echo "Setting milestone $MILESTONE_TITLE" for PR $PR_NUM
            echo "Linked Issue Number: $LINKED_ISSUE_NUM"
            echo "Processing PR #$PR_NUM..."
            gh pr edit $PR_NUM --milestone $MILESTONE_TITLE
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
